feat: compose functions
helderburato/maximus pull request #31
Opened 2020-11-28 22:10 UTC by karranb

Basic implementation of pipe and reduce.

I'm having a little hard time thinking about the descriptions of the function and I'm also open to implementing more test cases if anyone got some suggestions.

2020-11-29 21:20 UTC, helderburato commented on src/common/compose/test.js
> +  })
I think you can break each `expect` as a different test case, to be more readable and focus each test on just one thing.

2020-11-29 21:20 UTC, helderburato commented on src/common/pipe/test.js
> +    expect(multiply2).toBeCalled()
Same here.

2020-11-29 21:23 UTC, helderburato requested changes
I think the test-cases can be more broken into smaller parts and don't forget to generate the docs. markdown for every implemented function, if you need some help to make this, just ping me 💯 great work!

2020-11-30 13:19 UTC, karranb commented
I made a small refactor.
- Instead of breaking the tests into 3 cases, I broke them into 2. (I'm not sure if that's okay)
- I also created an `applyTo` based on `ramda's` one to use on the compose functions.https://ramdajs.com/docs/#applyTo (I'm not sure if that's okay too)

2020-11-30 15:09 UTC, helderburato approved these changes
Amazing! 💯 
Feel free to merge and close the related issues @karranb

2020-11-30 18:42 UTC, merged